from __future__ import annotations

import glob
import os
import shlex
import stat
import tempfile
from pathlib import Path
from typing import Iterable

from .db import Database
from .paths import managed_ssh_config_path, original_ssh_config_path


class SSHConfigError(RuntimeError):
    pass


def quote_value(value: str) -> str:
    if not value or any(ch.isspace() or ch in {'"', "'", "#", "\\"} for ch in value):
        return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'
    return value


def split_config_line(line: str) -> list[str]:
    """Tokenize one OpenSSH config line.

    On Windows a backslash is a path separator, not an escape character, so
    it is preserved before POSIX-style quote handling is applied.
    """
    if os.name == "nt":
        line = line.replace("\\", "\\\\")
    try:
        return shlex.split(line, comments=True, posix=True)
    except ValueError:
        return []


def _parse_include_tokens(line: str) -> list[str]:
    tokens = split_config_line(line)
    if not tokens or tokens[0].casefold() != "include":
        return []
    return tokens[1:]


def _expand_include(pattern: str, parent: Path) -> list[Path]:
    expanded = os.path.expanduser(pattern)
    path = Path(expanded)
    if not path.is_absolute():
        path = parent / path
    return [Path(item).resolve() for item in sorted(glob.glob(str(path)))]


def includes_target(config: Path, target: Path, seen: set[Path] | None = None) -> bool:
    config = config.expanduser().resolve()
    target = target.expanduser().resolve()
    if not config.exists():
        return False
    seen = seen or set()
    if config in seen:
        return False
    seen.add(config)
    try:
        lines = config.read_text(encoding="utf-8").splitlines()
    except (OSError, UnicodeError):
        return False
    for line in lines:
        for token in _parse_include_tokens(line):
            expanded = os.path.expanduser(token)
            candidate = Path(expanded)
            if not candidate.is_absolute():
                candidate = config.parent / candidate
            try:
                if candidate.resolve() == target:
                    return True
            except OSError:
                pass
            for include in _expand_include(token, config.parent):
                if include == target or includes_target(include, target, seen):
                    return True
    return False


def _render_server(server: dict, credential: dict | None) -> list[str]:
    lines = [
        f"Host {server['alias']}",
        f"  HostName {quote_value(server['hostname'])}",
        f"  Port {server['port']}",
        f"  User {quote_value(server['username'])}",
    ]
    jumps = server["proxy_jumps"]
    lines.append(f"  ProxyJump {','.join(jumps) if jumps else 'none'}")
    if credential and credential["kind"] == "password":
        lines.extend(
            [
                "  IdentityFile none",
                "  IdentitiesOnly yes",
                "  PubkeyAuthentication no",
                "  PasswordAuthentication yes",
                "  KbdInteractiveAuthentication yes",
                "  PreferredAuthentications keyboard-interactive,password",
            ]
        )
    elif credential and credential["kind"] == "key":
        lines.extend(
            [
                f"  IdentityFile {quote_value(credential['key_path'])}",
                "  IdentitiesOnly yes",
                "  PubkeyAuthentication yes",
                "  PreferredAuthentications publickey",
            ]
        )
    lines.append("")
    return lines


def render_config(
    database: Database,
    *,
    destination: str | Path | None = None,
    original: str | Path | None = None,
) -> Path:
    destination_path = Path(destination) if destination else managed_ssh_config_path()
    original_path = Path(original) if original else original_ssh_config_path()
    destination_path = destination_path.expanduser().resolve()
    original_path = original_path.expanduser().resolve()
    if includes_target(original_path, destination_path):
        raise SSHConfigError(
            f"refusing to create an Include cycle: {original_path} already includes {destination_path}"
        )
    lines = [
        "# Generated by ssh-server-manager. Do not edit this file directly.",
        "# Edit hosts with serverctl or the local UI.",
        "",
    ]
    credentials = {item["id"]: item for item in database.list_credentials()}
    for server in database.list_servers():
        lines.extend(_render_server(server, credentials.get(server["credential_id"])))
    if original_path.exists() and original_path != destination_path:
        lines.extend([f"Include {quote_value(str(original_path))}", ""])
    content = "\n".join(lines)
    destination_path.parent.mkdir(parents=True, exist_ok=True)
    if os.name != "nt":
        destination_path.parent.chmod(stat.S_IRWXU)
    file_descriptor, temporary = tempfile.mkstemp(prefix=".ssh-server-manager-", dir=destination_path.parent)
    temporary_path = Path(temporary)
    try:
        with os.fdopen(file_descriptor, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        if os.name != "nt":
            temporary_path.chmod(stat.S_IRUSR | stat.S_IWUSR)
        os.replace(temporary_path, destination_path)
    finally:
        temporary_path.unlink(missing_ok=True)
    return destination_path


def effective_config_args(database: Database) -> list[str]:
    return ["-F", str(render_config(database))]

