name: test

on:
  push:
  pull_request:

jobs:
  cross-platform:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: python -m pip install -e "./ssh-server-manager[test]"
      - run: python -m pytest ssh-server-manager/tests
      - run: python -m compileall -q ssh-server-manager/scripts

